src/Entity/Author.php
<?php

namespace App\Entity;

use App\Formatter\NameFormatter;

use App\Repository\AuthorRepository;

use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\OneToMany(targetEntity="App\Entity\Book", mappedBy="author") */
    private $books;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Podaj imię.")
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Podaj nazwisko.")
     */
    private $last_name;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    /** @return Collection|Book[] */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getFirstName(): ?string
    {
        return NameFormatter::formatName($this->first_name);
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return NameFormatter::formatName($this->last_name);
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;

use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Author", inversedBy="books")
     * @Assert\NotNull(message="Wybierz autora książki lub dodaj nowego.")
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Podaj tytuł książki.")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=4)
     * @Assert\Range(
     *      min = 1800,
     *      max = "today",
     *      notInRangeMessage = "Wybierz rok pomiędzy {{ min }} a {{ max }}.",
     * )
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="Podaj numer ISBN.")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string")
     */
    private $coverFileName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function hasImage(): bool
    {
        return $this->getCoverFileName() ? true : false;
    }

    public function getCoverFilePath($default = true): ?string
    {
        return $this->getCoverFileName() ? 'uploads/covers/'.$this->getCoverFileName() : ($default ? 'images/defaultCover.png' : '');
    }

    public function getCoverFileName(): ?string
    {
        return $this->coverFileName;
    }

    public function setCoverFileName(string $coverFileName): self
    {
        $this->coverFileName = $coverFileName;

        return $this;
    }
}

src/Form/Type/BookType.php
<?php
namespace App\Form\Type;

use App\Entity\{Book, Author};

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('author', EntityType::class, [
                'class' => Author::class,
                'label' => 'Autor',
                'choice_label' => 'last_name',
                'data' => $options['author'] ?? null,
                'invalid_message' => 'Wybierz autora z listy lub dodaj nowego.'
            ])
            ->add('title', TextType::class, [
                'label' => 'Tytuł',
                'empty_data' => '',
                'invalid_message' => 'Podaj tytuł książki.'
            ])
            ->add('year', ChoiceType::class, [
                'label' => 'Rok wydania',
                'choices' => $this->prepareYearsSinceTo(1800),
                'empty_data' => ' ',
                'invalid_message' => 'Podaj rok wydania książki.'
            ])
            ->add('isbn', TextType::class, [
                'label' => 'ISBN',
                'empty_data' => '',
                'invalid_message' => 'Podaj numer ISBN.'
            ])
            ->add('cover', FileType::class, [
                'label' => 'Okładka (png, jpg, jpeg)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5120k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpg',
                            'image/jpeg'
                        ],
                        'mimeTypesMessage' => 'Dozwolony format pliku to PNG, JPG i JPEG.',
                    ])
                ],
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
            'author' => null
        ]);
    }

    private function prepareYearsSinceTo($min, $max = null)
    {
        $years = range($min, ($max ?: date('Y')) );

        $years = array_combine($years, $years);

        return array_reverse($years, true);
    }
}

src/Controller/BooksController.php
<?php
namespace App\Controller;

use App\Entity\{Book, Author};
use App\Form\Type\BookType;

use App\Service\FileManager;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BooksController extends Controller{

    /** @Route("/books", name="books.index") */
    public function index(){
        
        $authors = $this->repository(Author::class)->findAll();

        return $this->render('books/index.html.twig', compact('authors'));
    }

    /** @Route("/books/search", name="books.search") */
    public function search(Request $request){

        $filters = $request->request->all();

        $booksQuery = $this->repository(Book::class)->search($filters, true);

        $books = $this->paginate($booksQuery, $filters['page'], $filters['per_page']);

        return $this->render('/books/partial/booksList.html.twig', compact('books'));
    }

    /** @Route("/books/{id}", name="books.show", requirements={"id":"\d+"}) */
    public function show(Book $book){

        return $this->render('books/show.html.twig', compact('book'));
    }
    
    /** @Route("/books/create/{author}", name="books.create") */
    public function create(Author $author = null, Request $request){
        
        $form = $this->createForm(BookType::class, new Book, ['author' => $author]);

        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid())
            return $this->saveAndRedirect($form);
        
        return $this->render('books/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /** @Route("/books/update/{id}", name="books.update", requirements={"id":"\d+"}) */
    public function update(Book $book, Request $request){

        $form = $this->createForm(BookType::class, $book, ['author' => $book->getAuthor()]);

        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid())
            return $this->saveAndRedirect($form);
        
        return $this->render('books/update.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /** @Route("/books/delete/{id}", name="books.delete", methods="DELETE", requirements={"id": "\d+"}) */
    public function delete(Book $book){
        
        $this->repository(Book::class)->delete($book);

        return $this->redirectToRoute('books.index');
    }

    /** @Route("/books/delete-cover/{id}", name="books.delete-cover", methods="GET", requirements={"id": "\d+"}) */
    public function deleteCover(Book $book){
        
        $this->repository(Book::class)->deleteCover($book);

        return $this->redirectToRoute('books.show', ['id' => $book->getId()]);
    }

    private function saveAndRedirect($form){

        $book = $this->repository(Book::class)->saveByForm($form);

        return $this->redirectToRoute('books.show', ['id' => $book->getId()]);
    }
}

templates/books/create.html.twig
{% extends "base.html.twig" %}

{% set navSecondLevel = {name: "Książki", url: path('books.index')} %}
{% set navThirdLevel = {name: "Tworzenie"} %}

{% form_theme form 'form/basic.html.twig' %}

{% block content %}

    {{ form(form) }}

{% endblock %}

templates/books/index.html.twig
{% extends "base.html.twig" %}

{% set navSecondLevel = {name: "Książki", url: path('books.index')} %}

{% block content %}

    {% include 'components/btn/create.html.twig' with {url: path('books.create'), label: 'Dodaj książkę'} %}

    <div class="mt-4">
        <h2 class="mb-3">Lista książek:</h2>

        <div class="row">
            <div id="searchForm" class="mb-4 col-md-4 border-right">
                <div class="form-group form-inline">
                    <label for="id">Ilość na stronie:</label>&nbsp;
                    <select name="per_page" class="form-control">
                        {% for count in [5, 10, 20, 50, 100] %}
                            <option value="{{ count }}">{{ count }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group form-inline">
                    <label for="id">ID:</label>&nbsp;
                    <input name="id" type="number" class="form-control"></input>
                </div>

                <div class="form-group form-inline">
                    <label for="title">Tytuł: </label>&nbsp;
                    <input name="title" type="text" class="form-control"></input>
                </div>

                <div class="form-group form-inline">
                    <label for="author">Autor: </label>&nbsp;
                    <select name="author" class="form-control">
                        <option value="">Wszyscy</option>
                        {% for author in authors %}
                            <option value="{{ author.id }}">{{ author.getFullName }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group form-inline">
                    <label for="author">Sortowanie: </label>&nbsp;
                    <select name="sort" class="form-control">
                        <option value="latest">Data dodania: najnowsze</option>
                        <option value="oldest">Data dodania: najstarsze</option>
                        <option value="published_latest">Rok wydania: najnowsze</option>
                        <option value="published_oldest">Rok wydania: najstarsze</option>
                    </select>
                </div>

                <button id="searchBtn" class="btn btn-success">Szukaj</button>
            </div>
            <div class="col-md-8 pl-2">
                <div id="books">        
                </div>
        </div>

    </div>

{% endblock %}

{% block footerJS %}

    {{ parent() }}
    <script src="/js/AjaxPagination.js"></script>
    <script>
        Pagination.callbackFunction = search;
        PaginationEffects.loadingElem = $('#books');

        let form = $('#searchForm');
        let perPage = form.find('[name="per_page"]'),
            id = form.find('[name="id"]'),
            title = form.find('[name="title"]'),
            author = form.find('[name="author"]');

        $('#searchBtn').click(() => {refresh()});
        form.find('select').on('change', () => {refresh()});
        form.on('keypress', function(e){
            if( e.which == 13 )
                refresh()
        });


        function refresh(){
            Pagination.currentPage = 1;

            search();
        }
        
        search();

        function search(page = 1){
            PaginationEffects.loadOpacityEffect(true);

            $.ajax({
                url: "{{ path('books.search') }}",
                type: "POST",
                dataType: "HTML",
                data: {
                    id: id.val(),
                    title: `%${title.val()}%`,
                    author: author.val(),
                    sort: $('[name="sort"]').val(),
                    page: Pagination.currentPage,
                    per_page: perPage.val()
                }
            })
            .done(function(response){
                PaginationEffects.showDataWithEffect( response )
            })
        }
    </script>

{% endblock %}

templates/books/show.html.twig
{% extends "base.html.twig" %}

{% set navSecondLevel = {name: "Książki", url: path('books.index')} %}
{% set navThirdLevel = {name: "Podgląd"} %}

{% block content %}

    <div class="bookPreview">
        <h2>{{ book.title }}</h2>

        <div class="my-2">
            {% if book.hasImage() %}
                <img src="{{ asset(book.getCoverFilePath()) }}"></img>
            {% else %}
                <i class="fas fa-camera"></i> Nie dodano zdjęcia okładki.
            {% endif %}
        </div>
        
        Autor: <a href="{{ path('authors.show', {id: book.author.id}) }}">{{ book.author.fullName }}</a><br>
        Rok wydania: {{ book.year}}<br>
        ISBN: {{ book.isbn }}<br>

        <div class="mt-4 form-group form-inline">
            {% include 'components/btn/edit.html.twig' with {url: path('books.update', {id: book.id})} %}
            &nbsp;
            {% if book.hasImage() %}
                {% include 'components/btn/edit.html.twig' with {url: path('books.delete-cover', {id: book.id}), label: 'Usuń zdjęcie'} %}
                &nbsp;
            {% endif %}
            {% include 'components/btn/delete.html.twig' with {url: path('books.delete', {id: book.id})} %}
        </div>
    </div>
{% endblock %}

templates/books/update.html.twig
{% extends "base.html.twig" %}

{% set navSecondLevel = {name: "Książki", url: path('books.index')} %}
{% set navThirdLevel = {name: "Edycja"} %}

{% form_theme form 'form/basic.html.twig' %}

{% block content %}

    {{ form(form) }}

{% endblock %}